### ISSUE TITLE
Branches

### ISSUE THREAD

**Issue by jhauswald** [claritylab/clarity-mobile#2]
There are 3 branches currently, we don't need the sirius one after the PR merge right? @twurman

**Comment by twurman** [comment]
We can delete the Sirius branch, or leave it because I can Reuse it for V0.2

On Wednesday, July 8, 2015, Johann Hauswald notifications@github.com
wrote:

> There are 3 branches currently, we don't need the sirius one after the PR
> merge right? @twurman https://github.com/twurman
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/claritylab/clarity-mobile/issues/2.

## 

Timothy R. Wurman
University of Michigan
BSE Computer Science
twurman@umich.edu | 978-760-2208

**Comment by jhauswald** [comment]
ok up to you

**Comment by jhauswald** [comment]
I think the branches are out of sync: you made changes to sirius, dev and master. If you make tweaks, first make them on the branch, then merge it in. The branches need to stay even.

**Comment by twurman** [comment]
Had to add some missing files for it to work immediately on cloning, which is when there are more changes to the sirius branch. I'm not sure what you mean about changes to all three branches
